# specify a directory to install
cask_args appdir: '/Applications'
# install packages
brew 'coreutils'
brew 'starship'
brew 'automake'
brew 'autoconf'
brew 'openssl'
brew 'libyaml'
brew 'readline'
brew 'gnupg'
brew 'libxslt'
brew 'libtool'
# brew 'unixodbc'
brew 'asdf'
brew 'git'
brew 'bash-completion'
brew 'tree'
brew 'rg'
brew 'zoxide'
brew 'fzf'
brew 'direnv'
# brew 'node'
brew 'fzy'
# cask 'hyper'
# need to install java before jenkins
# cask 'java'
brew 'wget'
# Casks
# cask 'google-chrome'
# cask 'alfred'
# cask 'flux'
# cask '1password'
cask 'iterm2'
brew 'bat'
# brew 'vim'
brew 'fx'
# brew 'go'
cask 'gifcapture'
brew 'lsd'
